version: '3'
services:
    api:
        container_name: node-boilerplate
        image: node:16
        working_dir: /usr/src/app
        restart: always
        command: bash -c "yarn install --only=prod && yarn debug"
        volumes:
            - ./dist/:/usr/src/app/dist/
            - ./package.json:/usr/src/app/package.json
        ports:
            - '5000:5000'
            - '9222:9222'
        networks:
            - tool-node-boilerplate
        #depends_on:
        #    - mongo
networks:
    tool-node-boilerplate:
        driver: bridge
#volumes:
#    mongo-data:
#        driver: local
